version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: dhobi-backend
    env_file:
      - ./backend/.env
    ports:
      - "9000:9000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: dhobi-frontend
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - backend
